### ISSUE TITLE
Update SpotifyService song recommendation params

### ISSUE THREAD

**Issue by fentontaylor** [Guten-Reader/guten_reader_BE#11]
As a user, I should be able to send a request to `/api/v1/recommendation` and get a song that more accurately matches the mood with attributes `valence` and `mode`. For example, song params should be:
**Positive:** 
`{'valence': 1, 'mode': 1}`
**Neutral:** 
`{'valence': 0.5}`
**Negative:** 
`{'valence': 0, 'mode': 0}`

**Comment by MackHalliday** [comment]
Completed and deployed
